export const CONFIG = {
  SUPABASE_URL: "https://SEU-PROJETO.supabase.co",
  SUPABASE_ANON_KEY: "SUA_CHAVE_ANON_OU_PUBLISHABLE",
  CONSENT_VERSION: "TCLE-v1.0",
  CONSENT_URL: "COLE_AQUI_O_LINK_DO_TCLE_APROVADO",
  REQUIRED_RATERS: 6,
  I_CVI_THRESHOLD: 0.78,
  S_CVI_THRESHOLD: 0.90,
  STUDY_TITLE: "Validação Clínica do Corpus — LLM-Council em Farmacoterapia"
};
